### PR TITLE
Added explicit defaults

### PR DESCRIPTION
**Pull request by Glomels**

### CODE REVIEW

**Comment by Glomels** [comment]
one of my VS Code extension formatted the document and I didn't notice at first. I reverted it because I don't think it was cool to the push such changes just like that.

**Comment by akshat157** [comment]
@Glomels This looks good!

Just one potential improvement - Do you think that if we hover over other options (other than the active one) the current active should lose its `.active` class? i.e. only one from a list should have the `.active` class at any given time. I think it'll look nicer that way. Thoughts?

**Comment by Glomels** [comment]
> @Glomels This looks good!
> 
> Just one potential improvement - Do you think that if we hover over other options (other than the active one) the current active should lose its `.active` class? i.e. only one from a list should have the `.active` class at any given time. I think it'll look nicer that way. Thoughts?

I implemented it. I'll leave it to you to decide how it looks better.

**Comment by akshat157** [comment]
This works great! Thanks for the contribution @Glomels. :smile:

**Pull request merged**
