### PR TITLE
[New feature] Added immersive mode

### PR DESCRIPTION
**Pull request by Glomels**
Immersive mode to simply appreciate the scenery provided by the background picture.
UI components will toggle visibility when the ESC key is pressed down.
Defaults to false (visible components).

### CODE REVIEW

**Comment by akshat157** [comment]
That's a good feature! However, This PR was the only way I could understand what and how to use this mode. A cornered text with low opacity saying something like "Press Esc to enter Immersive Mode" can be helpful. Would you like to work on it?

**Comment by Glomels** [comment]
> That's a good feature! However, This PR was the only way I could understand what is this mode and how to use it. A cornered text with low opacity saying something like "Press `Esc` to enter Immersive Mode" can be helpful. Would you like to work on it?

Yeah sure, I'll do that

**Comment by akshat157** [comment]
Issue solved with #41

**Comment by akshat157** [comment]
Feature added with #41. Thank you for the inspiration of the idea! :)

**Pull request closed without merging**
