### PR TITLE
Added animation to playpause button 

### LINKED ISSUE #28: Improve hover animations for the control buttons.
The GIF in #26 shows a hover animation for the reset/restart button. It would be great to add that hover animation with a smooth transition to other control buttons!

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #28 

Added animation to playpause button with pure CSS only

Animation
This is the best i can make with 3d transforms😁

_I am a hacktoberfest contributor_

### CODE REVIEW

**Comment by ashuvssut** [comment]
sorry I forgot to add the hover effect. I will add it now

**Comment by ashuvssut** [comment]
hover effect added too

**Comment by ashuvssut** [comment]
I ud recommend using scss instead of css to better organize your styles in a structured way.
I you agree with this idea then I ud recommend to use `dart-sass`. 

Why only `dart-sass`?
`dart-sass` is the primary implementation of sass, which means it gets new features before any other implementation (eg `node-sass`, etc)

**Comment by ashuvssut** [comment]
**One more suggestion**
I ud suggest using `scss` instead of `css` to better organize your styles in a structured way.
If you agree with this idea then I ud recommend to use `dart-sass`.

Why only `dart-sass`?
`dart-sass` is the primary implementation of `sass`, which means it gets new features before any other implementations (eg `node-sass`, etc)

**Comment by akshat157** [comment]
> This is the best i can make with 3d transforms 😁 

Lol. I will take that, although, a simple transition would've worked too because I am trying to keep the UI minimal. Good work!

> Also i ud recommend to use modular css (import css as a module in jsx files) instead of directly importing them as normal css

I created this project while learning ReactJS, so the focus was more on it rather than CSS itself. I am happy to see you taking interest in it though. Feel free to create issues about modularizing the CSS or as you suggested, using `dart-sass`. Creating issues is same as contributing via PRs. If not you, someone else can work on them. :) Thanks for the suggestions!

**Pull request merged**
