### PR TITLE
Removed debug statements

### LINKED ISSUE #19: Remove debug statements
There are a lot of unnecessary `console.log()` debug statements all over the project. This can be a great first timer issue to solve. Do keep in mind not to remove any essential lines of code. :)

### PR DESCRIPTION
**Pull request by TechieNK**
Removed all the debug statements including previously commented lines `.js` and `.css`

Tasks Completed:

- [x] Fork & clone this repository
- [x] Removed all the debug statements and commented lines  `.js` and `.css`
- [x] Push changes to main
- [x] Submit pull request

This PR closes #19

Thank You

### CODE REVIEW

**Comment by TechieNK** [comment]
@akshat157 Kindly review this PR

**Comment by akshat157** [comment]
Hey @TechieNK, thanks for the contribution, unfortunately, I cannot approve the PR right now. I should have mentioned that I intend to keep the default comments (the ones that appear with the initialization) and the comments written to explain the code (Like for the circular progress bar). My bad.

Do you think you can revert these few changes? The intention is only to remove unnecessary console logs and unused styles (You can remove the empty classes after removing a commented line as well).

**Comment by TechieNK** [comment]
> Hey @TechieNK, thanks for the contribution, unfortunately, I cannot approve the PR right now. I should have mentioned that I intend to keep the default comments (the ones that appear with the initialization) and the comments written to explain the code (Like for the circular progress bar). My bad.
> 
> Do you think you can revert these few changes? The intention is only to remove unnecessary console logs and unused styles (You can remove the empty classes after removing a commented line as well).

Yeah I'll revert those

**Comment by TechieNK** [comment]
@akshat157 Kindly review this PR.

**Pull request merged**
