### PR TITLE
add title, app address, and license to README

### PR DESCRIPTION
**Pull request by ZaidMarrie**

### CODE REVIEW

**Comment by akshat157** [comment]
Good work @ZaidMarrie ! I have made a correction to the title. However, you missed the app preview address: https://akshat157.github.io/meditate-app. You can add it somewhere around the overview section.

**Comment by ZaidMarrie** [comment]
I have added the app preview address

**Comment by ZaidMarrie** [comment]
meditate-app-README-md-at-main-·-ZaidMarrie-meditate-app

**Comment by akshat157** [comment]
Oops. My bad. Did not notice it. I was expecting something like "The app can be previewed here" or something with a proper description like "A meditation assistant.." or something. Anyways, this LGTM! I'll merge it. Thanks for the contribution.

**Pull request merged**
